// Generated by CoffeeScript 1.6.3
(function() {
  var ModelInitializer;

  ModelInitializer = require("" + __dirname + "/model");

  exports.requirements = ["initializers.relational"];

  exports.plugin = function() {
    return ModelInitializer;
  };

}).call(this);
