// Generated by CoffeeScript 1.6.2
(function() {
  var ModelInitializer;

  ModelInitializer = require("" + __dirname + "/model");

  exports.requirements = ["initializers.relational"];

  exports.plugin = function(Relational) {
    ModelInitializer.use("Relational", Relational);
    return ModelInitializer;
  };

}).call(this);
