// Generated by CoffeeScript 1.4.0

/*
  This "plugin" is a vanilla mongoose plugin
*/


(function() {
  var __slice = [].slice;

  exports.plugin = function(schema, options) {
    var childModel, childName, childSchema;
    childName = options.child.name;
    childSchema = options.child.schema;
    childModel = options.child.model;
    return schema.methods[childName] = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      console.log("getting child documents");
      return console.log("extracted own query- ");
    };
  };

}).call(this);
