// Generated by CoffeeScript 1.4.0

/*
  Responsible for defining all the relational operations between
  schemas as defined by a valid relation.json config file
*/


(function() {
  var MongoRelational, MongooseChild, NodeManager,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NodeManager = require("" + __dirname + "/node_manager");

  MongooseChild = require("" + __dirname + "/mongoose_child");

  MongoRelational = (function() {
    /*
        Method: constructor
        
        Delegates build operations to build
        specific _relation object
    */

    function MongoRelational(schemas) {
      this.addRelationship = __bind(this.addRelationship, this);
      this._schemas = schemas;
      this._nodeManager = new NodeManager();
    }

    /*
        Method: addRelationship  (Synchronous)
    
        Creates a relationship between node1 and node2 of type, type. Valid
        types are
          "parent_child"
          "orphan"
    
        Orphan types will add the model to the orphaned collections.
    */


    MongoRelational.prototype.addRelationship = function(type, sNames) {
      var child, childName, options, orphan, parent, parentName;
      if (type === "parent_child") {
        parentName = sNames.parent;
        childName = sNames.child;
        console.log("pc " + parentName + " - " + childName);
        parent = this._schemas[parentName];
        child = this._schemas[childName];
        options = {
          child: {
            name: childName,
            schema: child
          }
        };
        return parent.plugin(MongooseChild.plugin, options);
      } else if (type === "orphan") {
        return orphan = sNames.orphan;
      } else {
        return console.log("Invalid type " + type);
      }
    };

    return MongoRelational;

  })();

  module.exports = MongoRelational;

}).call(this);
