// Generated by CoffeeScript 1.4.0
(function() {
  var NodeManager;

  NodeManager = (function() {

    function NodeManager() {}

    NodeManager.prototype.addChild = function(parent, child) {};

    NodeManager.prototype.orphan = function() {};

    return NodeManager;

  })();

  module.exports = NodeManager;

}).call(this);
