// Generated by CoffeeScript 1.4.0

/*
  A small mongoose adapter that transforms schemas from class-like coffeescript classes
  into the more idosyncratic mongoose plugin interface
*/


(function() {

  exports.adapt = function(schema, options, plugin) {
    var _plugin;
    _plugin = function(skema, options) {
      var pluginMethodDefinition, pluginMethodName, _ref, _results;
      _ref = plugin.prototype;
      _results = [];
      for (pluginMethodName in _ref) {
        pluginMethodDefinition = _ref[pluginMethodName];
        if (pluginMethodName === 'constructor') {
          continue;
        }
        _results.push(skema.methods[pluginMethodName] = pluginMethodDefinition);
      }
      return _results;
    };
    return schema.plugin(_plugin, options);
  };

}).call(this);
