// Generated by CoffeeScript 1.4.0

/*
  Exports a function that enriches parent schema
  with access to children...taking into account ownership etc...

  Eg. A teacher owns classes, so the teacher schema would be enriched
      with teacher.classes()
*/


(function() {



}).call(this);
