// Generated by CoffeeScript 1.6.2
(function() {
  var loader, modules, plugin;

  plugin = require("plugin");

  loader = plugin.require("core");

  loader.load(function(err) {
    if (err != null) {
      return console.error(err.stack);
    }
  });

  modules = {};

}).call(this);
