// Generated by CoffeeScript 1.4.0
(function() {
  var BaseBuilder, fs;

  fs = require("fs");

  /*
    Class: BaseBuilder
  
    Implements some common functionality between builders.
  */


  BaseBuilder = (function() {

    function BaseBuilder() {}

    return BaseBuilder;

  })();

  module.exports = BaseBuilder;

}).call(this);
