// Generated by CoffeeScript 1.4.0
(function() {
  var Permission;

  Permission = (function() {
    var R, RW, RWD, SUPER;

    R = 0;

    RW = 1;

    RWD = 2;

    SUPER = 3;

    function Permission(pLevel) {
      this._pLevel = pLevel;
    }

    Permission.prototype.__defineGetter__('level', function() {
      return this._pLevel;
    });

    return Permission;

  })();

  module.exports = Permission;

}).call(this);
