// Generated by CoffeeScript 1.4.0
(function() {
  var Permission;

  Permission = (function() {
    var R, RW, RWD, SUPER;

    R = 0;

    RW = 1;

    RWD = 2;

    SUPER = 3;

    function Permission(ownerResource, pLevel) {
      this._owner = ownerResource;
      this._pLevel = pLevel;
    }

    /*
        Method: serialize
    
        Creates a permission object consistent
        with the applications permission schema.
    */


    Permission.prototype.serialize = function() {
      var p;
      p = {
        _id: this._owner.id,
        l: this._pLevel
      };
      return p;
    };

    /*
        Equality methods
    */


    Permission.prototype.gt = function(pObj) {
      return this._pLevel > pObj.l;
    };

    Permission.prototype.gte = function(pObj) {
      return this._pLevel >= pObj.l;
    };

    Permission.prototype.lt = function(pObj) {
      return this._pLevel < pObj.l;
    };

    Permission.prototype.lte = function(pObj) {
      return this._pLevel <= pObj.l;
    };

    Permission.prototype.__defineGetter__('level', function() {
      return this._pLevel;
    });

    return Permission;

  })();

  module.exports = Permission;

}).call(this);
