// Generated by CoffeeScript 1.6.2
(function() {
  var RelationProxy;

  RelationProxy = require("" + __dirname + "/relation_proxy");

  /*
    This "plugin" is a vanilla mongoose plugin
  
    Does two things.
  
    1. Adds the permission control field for the parent object into
    the child's schema.
  
    eg.  if teachers --(parentOf)-> classes
  
    then the classes schema will get a field called _teachers
  */


  exports.plugin = function(schema, options) {
    var childColl, childSchema, models, newChildSchemaField, parentColl, permissionSchema;

    models = options.mongoose.models;
    childSchema = options.child.schema;
    childColl = options.child.collectionName;
    parentColl = options.parent.collectionName;
    permissionSchema = options.permission.schema;
    newChildSchemaField = {};
    newChildSchemaField["_" + parentColl] = [permissionSchema];
    childSchema.add(newChildSchemaField);
    return schema.methods["" + childColl + "_"] = RelationProxy.handle(models, options.child);
  };

}).call(this);
